// 3dsaves OAuth relay
//
// The 3DS can't receive an HTTP redirect itself (the browser completing
// the Dropbox login runs on a phone, a different device), so it can't use
// a normal OAuth redirect_uri directly. This tiny Worker stands in for
// it: Dropbox redirects the phone here after the user approves, this
// stores the authorization code (keyed by a random `state` value the 3DS
// generated and put in the original authorize URL) for a few minutes, and
// the 3DS polls /poll?state=... until it shows up -- no typing needed.
//
// Security note: this only ever sees the OAuth *authorization code*, never
// the PKCE code_verifier (that's generated on the 3DS and never leaves it
// until the final token exchange, straight from the 3DS to Dropbox over
// HTTPS). A code without its paired verifier can't be redeemed for a
// token, so this relay being compromised or logged doesn't expose Dropbox
// account access -- see https://dropbox.tech/developers/pkce--what-and-why-
//
// `state` is a long random value generated by the 3DS (same CSPRNG as the
// PKCE verifier), so guessing someone else's in-flight state to poison or
// read their entry isn't practical.

const CODE_TTL_SECONDS = 300; // 5 minutes -- a login attempt shouldn't take longer than this

function htmlPage(title, message, ok, code) {
  const color = ok ? "#1a7f37" : "#cf222e";
  // The 3DS polls for this automatically, but show the raw code too as a
  // manual fallback in case polling doesn't reach it (relay hiccup, weird
  // network) -- there's no other way to get it once redirect_uri is in
  // play, since Dropbox no longer displays it on its own page.
  const codeBlock = code
    ? `<p>If it doesn't continue on its own, type this code on your 3DS instead:</p>
       <code style="display:block;word-break:break-all;background:#f0f2f4;
       padding:12px;border-radius:6px;font-size:1.1em;margin:12px 0">${code}</code>`
    : "";
  return `<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<style>
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  display:flex;align-items:center;justify-content:center;min-height:100vh;
  margin:0;background:#f6f8fa;color:#1f2328;text-align:center;padding:24px}
.card{max-width:420px}
h1{color:${color};font-size:1.3em}
</style></head>
<body><div class="card"><h1>${title}</h1><p>${message}</p>${codeBlock}</div></body></html>`;
}

async function handleCallback(url, env) {
  const state = url.searchParams.get("state");
  const code = url.searchParams.get("code");
  const error = url.searchParams.get("error_description") || url.searchParams.get("error");

  if (!state) {
    return new Response(htmlPage("Missing state", "This link is missing required information -- go back to your 3DS and try again.", false), {
      status: 400,
      headers: { "content-type": "text/html; charset=utf-8" },
    });
  }

  if (error) {
    await env.CODES.put(state, JSON.stringify({ error }), { expirationTtl: CODE_TTL_SECONDS });
    return new Response(htmlPage("Login cancelled", error, false), {
      headers: { "content-type": "text/html; charset=utf-8" },
    });
  }

  if (!code) {
    return new Response(htmlPage("Missing code", "Dropbox didn't send back an authorization code -- go back to your 3DS and try again.", false), {
      status: 400,
      headers: { "content-type": "text/html; charset=utf-8" },
    });
  }

  await env.CODES.put(state, JSON.stringify({ code }), { expirationTtl: CODE_TTL_SECONDS });

  return new Response(
    htmlPage("Linked!", "You can close this tab and go back to your 3DS -- it'll pick this up automatically.", true, code),
    { headers: { "content-type": "text/html; charset=utf-8" } }
  );
}

async function handlePoll(url, env) {
  const state = url.searchParams.get("state");
  if (!state) {
    return Response.json({ status: "error", error: "missing state" }, { status: 400 });
  }

  const raw = await env.CODES.get(state);
  if (!raw) {
    return Response.json({ status: "pending" });
  }

  // Single-use: delete on first successful read so a code can't be handed
  // out twice even if the 3DS's poll request gets retried.
  await env.CODES.delete(state);

  const data = JSON.parse(raw);
  if (data.error) {
    return Response.json({ status: "error", error: data.error });
  }
  return Response.json({ status: "ready", code: data.code });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname === "/callback") {
      return handleCallback(url, env);
    }
    if (url.pathname === "/poll") {
      return handlePoll(url, env);
    }
    return new Response("3dsaves OAuth relay -- see github.com/ljoaoml/3dsaves\n", {
      headers: { "content-type": "text/plain; charset=utf-8" },
    });
  },
};
